'use strict';
const stage=document.getElementById('stage');
const routes=['introduction','achievements','hobbies','facts'];
const labels=['Self introduction','Achievements','Hobbies','Random facts'];
const reduceQuery=window.matchMedia('(prefers-reduced-motion: reduce)');
let preference=false;
try{preference=localStorage.getItem('portfolio-reduce-motion')==='true';}catch{}
let data={name:'YuCheng',greeting:'Hi! I am',nickname:'You can also refer me as Nutcracker :D',intro:'I like turning ideas into websites, experimenting with AI, and figuring out how things work.',heroImage:'garden.svg',heroImageAlt:'Silver-blue leaves and ivory flowers against a dark background',artCaption:'Code. Curiosity. A few side quests.',achievements:[],hobbies:[],facts:[],contacts:[{label:'Email',type:'email',value:'cleavant666@gmail.com'},{label:'Discord',type:'copy',value:'nutcracker_cool'}]};
let active=0;let timers=[];let toastTimer;
const motionOff=()=>reduceQuery.matches||preference;
function n(tag,cls,text){const node=document.createElement(tag);if(cls)node.className=cls;if(text!=null)node.textContent=String(text);return node;}
function safeUrl(value,image=false){if(typeof value!=='string'||!value.trim())return '';if(image&&/^data:image\/(png|jpeg|webp|gif|avif);base64,[A-Za-z0-9+/=\s]+$/.test(value))return value;try{const url=new URL(value.replace(/^\/(?!\/)/,''),document.baseURI);return ['https:','http:'].includes(url.protocol)?url.href:'';}catch{return '';}}
function items(key){return Array.isArray(data[key])?data[key].filter(x=>x&&typeof x==='object'):[];}
function text(value,fallback=''){return typeof value==='string'?value:fallback;}
function toast(message){clearTimeout(toastTimer);document.getElementById('status').textContent=message;toastTimer=setTimeout(()=>{document.getElementById('status').textContent='';},4200);}
function piece(node,delay=0){if(!motionOff()){node.classList.add('build-piece');node.style.setProperty('--delay',delay+'ms');}return node;}
function heading(container,tag,full,cls){const h=n(tag,cls);h.id='slide-title';h.setAttribute('aria-label',full);const span=n('span','',full);span.setAttribute('aria-hidden','true');h.append(span);container.append(h);if(!motionOff()){span.textContent='';span.classList.add('typing-cursor');let at=0;const chars=Array.from(full);const tick=()=>{if(!span.isConnected)return;span.textContent=chars.slice(0,++at).join('');if(at<chars.length)timers.push(setTimeout(tick,25));else span.classList.remove('typing-cursor');};timers.push(setTimeout(tick,30));}return h;}
function introSlide(){
 const section=n('section','slide intro-slide');section.setAttribute('aria-labelledby','slide-title');const copy=n('div','intro-copy');copy.append(piece(n('p','eyebrow','01 / Self introduction')));
 const h=n('h1');h.id='slide-title';h.setAttribute('aria-label',`${text(data.greeting,'Hi! I am')} ${text(data.name,'YuCheng')} :D`);const visual=n('span');visual.setAttribute('aria-hidden','true');visual.append(n('span','greeting',text(data.greeting,'Hi! I am')));const name=n('span','hero-name');const nameText=n('span','',text(data.name,'YuCheng'));name.append(nameText,n('span','smile',':D'));visual.append(name);h.append(visual);copy.append(h);
 if(!motionOff()){const full=text(data.name,'YuCheng');nameText.textContent='';nameText.classList.add('typing-cursor');let i=0;const chars=Array.from(full);const tick=()=>{if(!nameText.isConnected)return;nameText.textContent=chars.slice(0,++i).join('');if(i<chars.length)timers.push(setTimeout(tick,70));else nameText.classList.remove('typing-cursor');};timers.push(setTimeout(tick,100));}
 copy.append(piece(n('p','nickname',text(data.nickname)),180),piece(n('p','intro-body',text(data.intro)),280));const explore=n('a','explore-link','Get to know me');explore.href='#achievements';explore.append(n('span','','↗'));copy.append(piece(explore,360));
 const figure=n('figure','intro-art');if(!motionOff())figure.classList.add('build-image');const source=safeUrl(data.heroImage,true);if(source){const image=n('img');image.src=source;image.alt=text(data.heroImageAlt);image.width=1586;image.height=992;figure.append(image);}const caption=n('figcaption');caption.append(n('span','',text(data.artCaption)),n('span','','✳'));figure.append(caption);section.append(copy,figure);return section;
}
function sectionFrame(index,title,subtitle){const section=n('section','slide');section.setAttribute('aria-labelledby','slide-title');const head=n('div','section-heading'),left=n('div');left.append(n('p','eyebrow',`${String(index+1).padStart(2,'0')} / ${labels[index]}`));heading(left,'h2',title);head.append(left,piece(n('p','section-subtitle',subtitle),120));section.append(head);return section;}
function emptyChapter(section,title,body){const empty=n('div','empty-chapter');empty.append(n('span','empty-number','—'));const copy=n('div');copy.append(n('h3','',title),n('p','',body));empty.append(copy,n('span','empty-decoration','✳'));section.append(piece(empty,140));}
function achievementsSlide(){const section=sectionFrame(1,'The little milestones.',text(data.achievementsIntro));const achievements=items('achievements').filter(x=>text(x.title));if(!achievements.length){emptyChapter(section,'Still writing this chapter.','A collection of achievements will live here.');return section;}const list=n('div','timeline');achievements.forEach((item,i)=>{const row=n('article','timeline-item');row.append(n('span','timeline-year',text(item.year)));const details=n('div');details.append(n('h3','',text(item.title)),n('p','',text(item.description)));row.append(details);const src=safeUrl(item.image,true);if(src){const image=n('img');image.src=src;image.alt=text(item.imageAlt,text(item.title));image.loading='lazy';row.append(image);}list.append(piece(row,140+i*70));});section.append(list);return section;}
function hobbiesSlide(){const section=sectionFrame(2,'For the fun of it.',text(data.hobbiesIntro));const list=n('div','hobby-grid');items('hobbies').filter(x=>text(x.title)).forEach((item,i)=>{const card=n('details','hobby-card');const summary=n('summary'),top=n('span','hobby-top');top.append(n('span','',String(i+1).padStart(2,'0')));const plus=n('span','hobby-plus','+');plus.setAttribute('aria-hidden','true');top.append(plus);summary.append(top,n('h3','',text(item.title)));card.append(summary,n('p','',text(item.description)));const src=safeUrl(item.image,true);if(src){const img=n('img');img.src=src;img.alt=text(item.imageAlt,text(item.title));img.loading='lazy';card.append(img);}list.append(piece(card,140+i*80));});if(!list.childElementCount)emptyChapter(section,'A few interests, coming soon.','There is always something new to get into.');else section.append(list);return section;}
function factsSlide(){const section=sectionFrame(3,'A little more me.',text(data.factsIntro));const grid=n('div','fact-grid');items('facts').filter(x=>text(x.title)).forEach((fact,i)=>{const card=n('button','fact-card');card.type='button';card.setAttribute('aria-pressed','false');const label=n('span','fact-label',`FACT ${String(i+1).padStart(2,'0')}`),content=n('span','fact-content',text(fact.title)),hint=n('span','fact-hint','Tap to reveal +');card.append(label,content,hint);card.addEventListener('click',()=>{const open=card.getAttribute('aria-pressed')!=='true';card.setAttribute('aria-pressed',String(open));content.textContent=open?text(fact.description):text(fact.title);hint.textContent=open?'Tap to turn back ↶':'Tap to reveal +';});grid.append(piece(card,140+i*80));});if(!grid.childElementCount)emptyChapter(section,'A little mystery for now.','Random facts will find their way here.');else section.append(grid);return section;}
function contacts(){const list=document.getElementById('contact-list');list.replaceChildren();items('contacts').forEach(contact=>{const value=text(contact.value).trim();if(!value)return;let control;if(contact.type==='copy'){control=n('button');control.type='button';control.dataset.copy=value;control.setAttribute('aria-label',`Copy ${text(contact.label)} ${value}`);}else{control=n('a');if(contact.type==='email'){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))return;control.href='mailto:'+encodeURIComponent(value).replace(/%40/g,'@');}else{const url=safeUrl(value);if(!url)return;control.href=url;control.target='_blank';control.rel='noopener noreferrer';}}control.append(document.createTextNode(text(contact.label,'Contact')),n('span','',value+(contact.type==='copy'?' ⧉':' ↗')));list.append(control);});}
function routeIndex(){const hash=location.hash.slice(1);return Math.max(0,routes.indexOf(hash));}
function draw(index,announce=false){timers.forEach(clearTimeout);timers=[];active=index;stage.classList.toggle('building',!motionOff());stage.replaceChildren([introSlide,achievementsSlide,hobbiesSlide,factsSlide][index]());document.querySelectorAll('[data-slide]').forEach(a=>{if(a.dataset.slide===routes[index])a.setAttribute('aria-current','page');else a.removeAttribute('aria-current');});document.getElementById('slide-current').textContent=String(index+1).padStart(2,'0');document.getElementById('slide-progress').style.width=((index+1)*25)+'%';document.getElementById('previous').disabled=index===0;document.getElementById('next').disabled=index===3;if(announce)toast(`${String(index+1).padStart(2,'0')} / ${labels[index]}`);}
function navigate(index){if(index<0||index>3)return;location.hash=routes[index];}
function updateMotion(){document.documentElement.classList.toggle('no-motion',motionOff());const button=document.getElementById('motion-toggle');button.textContent=motionOff()?'◌ Motion off':'◌ Motion on';button.setAttribute('aria-pressed',String(motionOff()));button.setAttribute('aria-label',reduceQuery.matches?'Motion off, following your device preference':(motionOff()?'Turn animations on':'Turn animations off'));button.disabled=reduceQuery.matches;}
window.addEventListener('hashchange',()=>draw(routeIndex(),true));
document.getElementById('previous').addEventListener('click',()=>navigate(active-1));document.getElementById('next').addEventListener('click',()=>navigate(active+1));
document.addEventListener('keydown',event=>{if(event.altKey||event.ctrlKey||event.metaKey||event.shiftKey||event.target.closest('input,textarea,select,[contenteditable=true]'))return;if(event.key==='ArrowRight'){event.preventDefault();navigate(active+1);}if(event.key==='ArrowLeft'){event.preventDefault();navigate(active-1);}});
document.getElementById('motion-toggle').addEventListener('click',()=>{preference=!preference;try{localStorage.setItem('portfolio-reduce-motion',String(preference));}catch{}updateMotion();draw(active);});reduceQuery.addEventListener('change',()=>{updateMotion();draw(active);});
document.addEventListener('click',async event=>{const button=event.target.closest('[data-copy]');if(!button)return;try{await navigator.clipboard.writeText(button.dataset.copy);toast('Copied: '+button.dataset.copy);}catch{toast('Discord: '+button.dataset.copy+' — select and copy the handle.');}});
stage.addEventListener('pointermove',event=>{if(motionOff()||event.pointerType!=='mouse')return;const art=stage.querySelector('.intro-art');if(!art)return;const bounds=stage.getBoundingClientRect();art.style.setProperty('--pan-x',((event.clientX-bounds.left)/bounds.width-.5)*10+'px');art.style.setProperty('--pan-y',((event.clientY-bounds.top)/bounds.height-.5)*8+'px');});stage.addEventListener('pointerleave',()=>{const art=stage.querySelector('.intro-art');if(art){art.style.setProperty('--pan-x','0px');art.style.setProperty('--pan-y','0px');}});
updateMotion();
fetch('portfolio.json',{cache:'no-cache'}).then(r=>{if(!r.ok)throw new Error('unavailable');return r.json();}).then(content=>{if(!content||typeof content!=='object'||Array.isArray(content))throw new Error('invalid');data=content;document.title=`${text(data.name,'YuCheng')} / A little about me`;document.querySelector('meta[name="description"]').content=`${text(data.greeting)} ${text(data.name)}. ${text(data.nickname)}`;contacts();draw(routeIndex());}).catch(()=>{draw(routeIndex());toast('The latest content could not load. Please refresh to try again.');});
